### ISSUE TITLE
Use a Syntax Highlighting library for the "documentation" sections

### ISSUE THREAD

**Issue by jtrenaud1s** [paulfears/graphs#4]
some syntax highlighting in a <\pre>style<\/pre>

**Comment by jtrenaud1s** [comment]
Here, ezpz, https://highlightjs.org/usage/

**Comment by jtrenaud1s** [comment]
The bare minimum for using highlight.js on a web page is linking to the library along with one of the styles and calling highlightAll:

```
<link rel="stylesheet" href="/path/to/styles/default.css">
<script src="/path/to/highlight.min.js"></script>
<script>hljs.highlightAll();</script>
```

This will find and highlight code inside of `<pre><code>` tags; it tries to detect the language automatically. If automatic detection doesn’t work for you, you can specify the language in the class attribute:

`<pre><code class="html">...</code></pre>`

**Comment by paulfears** [comment]
Fixed
